baseURL: https://huilun-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Huilun Hu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: Get Started
    subtitle: |-
      Here I will share about my overseas study and daily life experiences.
    title: Welcome to Huilun's website
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park, NW1
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: hhu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (793) 441-1423 
        title: Phone
  custom_css: []
  custom_js: []
  description: Hi, I'm Huilun, currently a MFA student at London Business School
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/HuilunH
      - icon: fa-github
        label: GitHub
        url: https://github.com/huilun910
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/huilun-hu
  image: ''
  name: Huilun
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
    menu: Menu
    title: Huilun
    subtitle: Portfolio Website
  tiles:
    enable: yes
    showcase:
      - image: hl1.jpg
        subtitle: Hello world
        title: About me
        url: blogs/about_me
      - image: Shanghai.jpg
        subtitle: Yangtze River Delta
        title: Field Trip to China
        url: blogs/china_field
      - image: GDP_cover.jpg
        subtitle: India, Germany, US
        title: GDP Components Analysis
        url: blogs/gdp_countries
      - image: bike.jpg
        subtitle: Monthly Changes in TfL bike rentals 
        title: Excess Rentals in TfL Bike Sharing
        url: blogs/tfl_bike
      - image: resume.jpg
        subtitle: Huilun's resume
        title: Huilun's Work Profile
        url: blogs/cv
      - image: Hangzhou.jpg
        subtitle: My Hometown
        title: A Glimpse of Hangzhou
        url: blogs/hangzhou
 
